# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: base.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'base.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbase.proto\x12\x04\x62\x61se\"\'\n\nTrafficEnv\x12\x0c\n\x04open\x18\x01 \x01(\x08\x12\x0b\n\x03\x65nv\x18\x02 \x01(\t\"\xbf\x01\n\x04\x42\x61se\x12\x0e\n\x06log_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63\x61ller\x18\x02 \x01(\t\x12\x0c\n\x04\x61\x64\x64r\x18\x03 \x01(\t\x12\x0e\n\x06\x63lient\x18\x04 \x01(\t\x12%\n\x0btraffic_env\x18\x05 \x01(\x0b\x32\x10.base.TrafficEnv\x12$\n\x05\x65xtra\x18\x06 \x03(\x0b\x32\x15.base.Base.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x8f\x01\n\x08\x42\x61seResp\x12\x16\n\x0estatus_message\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x12(\n\x05\x65xtra\x18\x03 \x03(\x0b\x32\x19.base.BaseResp.ExtraEntry\x1a,\n\nExtraEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BASE_EXTRAENTRY']._loaded_options = None
  _globals['_BASE_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_BASERESP_EXTRAENTRY']._loaded_options = None
  _globals['_BASERESP_EXTRAENTRY']._serialized_options = b'8\001'
  _globals['_TRAFFICENV']._serialized_start=20
  _globals['_TRAFFICENV']._serialized_end=59
  _globals['_BASE']._serialized_start=62
  _globals['_BASE']._serialized_end=253
  _globals['_BASE_EXTRAENTRY']._serialized_start=209
  _globals['_BASE_EXTRAENTRY']._serialized_end=253
  _globals['_BASERESP']._serialized_start=256
  _globals['_BASERESP']._serialized_end=399
  _globals['_BASERESP_EXTRAENTRY']._serialized_start=209
  _globals['_BASERESP_EXTRAENTRY']._serialized_end=253
# @@protoc_insertion_point(module_scope)
