# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hw_ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hw_ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chw_ocr.proto\x12\x06hw_ocr\x1a\nbase.proto\"q\n\x0fTextRotatedRect\x12\n\n\x02x0\x18\x01 \x01(\x05\x12\n\n\x02y0\x18\x02 \x01(\x05\x12\n\n\x02x1\x18\x03 \x01(\x05\x12\n\n\x02y1\x18\x04 \x01(\x05\x12\n\n\x02x2\x18\x05 \x01(\x05\x12\n\n\x02y2\x18\x06 \x01(\x05\x12\n\n\x02x3\x18\x07 \x01(\x05\x12\n\n\x02y3\x18\x08 \x01(\x05\"\\\n\x05HwReq\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12\x11\n\timage_url\x18\x03 \x01(\t\x12\x18\n\x04\x62\x61se\x18\x04 \x01(\x0b\x32\n.base.Base\"\xa5\x01\n\x08OCRHwRsp\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12*\n\tline_poly\x18\x02 \x03(\x0b\x32\x17.hw_ocr.TextRotatedRect\x12\x11\n\tline_text\x18\x03 \x03(\t\x12#\n\tline_type\x18\x04 \x03(\x0e\x32\x10.hw_ocr.LineType\x12!\n\tbase_resp\x18\x05 \x01(\x0b\x32\x0e.base.BaseResp*0\n\x08LineType\x12\x12\n\x0eMachinePrinted\x10\x00\x12\x10\n\x0cHandwrittern\x10\x01\x32\x42\n\x0cOCRHwService\x12\x32\n\x0fGetGeneralHwOcr\x12\r.hw_ocr.HwReq\x1a\x10.hw_ocr.OCRHwRspb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hw_ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LINETYPE']._serialized_start=413
  _globals['_LINETYPE']._serialized_end=461
  _globals['_TEXTROTATEDRECT']._serialized_start=36
  _globals['_TEXTROTATEDRECT']._serialized_end=149
  _globals['_HWREQ']._serialized_start=151
  _globals['_HWREQ']._serialized_end=243
  _globals['_OCRHWRSP']._serialized_start=246
  _globals['_OCRHWRSP']._serialized_end=411
  _globals['_OCRHWSERVICE']._serialized_start=463
  _globals['_OCRHWSERVICE']._serialized_end=529
# @@protoc_insertion_point(module_scope)
