# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ocr_normal_pb2 as ocr__normal__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ocr_normal_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OCRServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadScreenImg = channel.unary_unary(
                '/ocr.OCRService/ReadScreenImg',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.OCRSerRsp.FromString,
                _registered_method=True)
        self.Read_Screen_Img = channel.unary_unary(
                '/ocr.OCRService/Read_Screen_Img',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.OCRSerRsp.FromString,
                _registered_method=True)
        self.ReadTextAndLocateChars = channel.unary_unary(
                '/ocr.OCRService/ReadTextAndLocateChars',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.CharLocateRsp.FromString,
                _registered_method=True)
        self.Read_text_and_locate_chars = channel.unary_unary(
                '/ocr.OCRService/Read_text_and_locate_chars',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.CharLocateRsp.FromString,
                _registered_method=True)
        self.LocateTextAdv = channel.unary_unary(
                '/ocr.OCRService/LocateTextAdv',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.TextLocateRsp.FromString,
                _registered_method=True)
        self.Locate_text_adv = channel.unary_unary(
                '/ocr.OCRService/Locate_text_adv',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.TextLocateRsp.FromString,
                _registered_method=True)
        self.ReadTextAndLocateCharsBatch = channel.unary_unary(
                '/ocr.OCRService/ReadTextAndLocateCharsBatch',
                request_serializer=ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.CharLocateBatchRsp.FromString,
                _registered_method=True)
        self.ReadScreenImgBatch = channel.unary_unary(
                '/ocr.OCRService/ReadScreenImgBatch',
                request_serializer=ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.OCRSerBatchRsp.FromString,
                _registered_method=True)
        self.LocateTextAdvBatch = channel.unary_unary(
                '/ocr.OCRService/LocateTextAdvBatch',
                request_serializer=ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.TextLocateBatchRsp.FromString,
                _registered_method=True)
        self.SensitiveWords = channel.unary_unary(
                '/ocr.OCRService/SensitiveWords',
                request_serializer=ocr__normal__pb2.OCRSerReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.SensitiveWordsRsp.FromString,
                _registered_method=True)
        self.SensitiveWordsBatch = channel.unary_unary(
                '/ocr.OCRService/SensitiveWordsBatch',
                request_serializer=ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.SensitiveWordsBatchRsp.FromString,
                _registered_method=True)
        self.PredictVideo = channel.unary_unary(
                '/ocr.OCRService/PredictVideo',
                request_serializer=ocr__normal__pb2.VideoPredictReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.TagPredictRsp.FromString,
                _registered_method=True)
        self.PredictImages = channel.unary_unary(
                '/ocr.OCRService/PredictImages',
                request_serializer=ocr__normal__pb2.ImagesPredictReq.SerializeToString,
                response_deserializer=ocr__normal__pb2.MTagPredictRsp.FromString,
                _registered_method=True)


class OCRServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadScreenImg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read_Screen_Img(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTextAndLocateChars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read_text_and_locate_chars(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocateTextAdv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Locate_text_adv(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadTextAndLocateCharsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadScreenImgBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LocateTextAdvBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensitiveWords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SensitiveWordsBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictImages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadScreenImg': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadScreenImg,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.OCRSerRsp.SerializeToString,
            ),
            'Read_Screen_Img': grpc.unary_unary_rpc_method_handler(
                    servicer.Read_Screen_Img,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.OCRSerRsp.SerializeToString,
            ),
            'ReadTextAndLocateChars': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTextAndLocateChars,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.CharLocateRsp.SerializeToString,
            ),
            'Read_text_and_locate_chars': grpc.unary_unary_rpc_method_handler(
                    servicer.Read_text_and_locate_chars,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.CharLocateRsp.SerializeToString,
            ),
            'LocateTextAdv': grpc.unary_unary_rpc_method_handler(
                    servicer.LocateTextAdv,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.TextLocateRsp.SerializeToString,
            ),
            'Locate_text_adv': grpc.unary_unary_rpc_method_handler(
                    servicer.Locate_text_adv,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.TextLocateRsp.SerializeToString,
            ),
            'ReadTextAndLocateCharsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadTextAndLocateCharsBatch,
                    request_deserializer=ocr__normal__pb2.OCRSerBatchReq.FromString,
                    response_serializer=ocr__normal__pb2.CharLocateBatchRsp.SerializeToString,
            ),
            'ReadScreenImgBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadScreenImgBatch,
                    request_deserializer=ocr__normal__pb2.OCRSerBatchReq.FromString,
                    response_serializer=ocr__normal__pb2.OCRSerBatchRsp.SerializeToString,
            ),
            'LocateTextAdvBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.LocateTextAdvBatch,
                    request_deserializer=ocr__normal__pb2.OCRSerBatchReq.FromString,
                    response_serializer=ocr__normal__pb2.TextLocateBatchRsp.SerializeToString,
            ),
            'SensitiveWords': grpc.unary_unary_rpc_method_handler(
                    servicer.SensitiveWords,
                    request_deserializer=ocr__normal__pb2.OCRSerReq.FromString,
                    response_serializer=ocr__normal__pb2.SensitiveWordsRsp.SerializeToString,
            ),
            'SensitiveWordsBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SensitiveWordsBatch,
                    request_deserializer=ocr__normal__pb2.OCRSerBatchReq.FromString,
                    response_serializer=ocr__normal__pb2.SensitiveWordsBatchRsp.SerializeToString,
            ),
            'PredictVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictVideo,
                    request_deserializer=ocr__normal__pb2.VideoPredictReq.FromString,
                    response_serializer=ocr__normal__pb2.TagPredictRsp.SerializeToString,
            ),
            'PredictImages': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictImages,
                    request_deserializer=ocr__normal__pb2.ImagesPredictReq.FromString,
                    response_serializer=ocr__normal__pb2.MTagPredictRsp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OCRService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ocr.OCRService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OCRService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadScreenImg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ReadScreenImg',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.OCRSerRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read_Screen_Img(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/Read_Screen_Img',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.OCRSerRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTextAndLocateChars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ReadTextAndLocateChars',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.CharLocateRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read_text_and_locate_chars(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/Read_text_and_locate_chars',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.CharLocateRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocateTextAdv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/LocateTextAdv',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.TextLocateRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Locate_text_adv(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/Locate_text_adv',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.TextLocateRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadTextAndLocateCharsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ReadTextAndLocateCharsBatch',
            ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
            ocr__normal__pb2.CharLocateBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadScreenImgBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/ReadScreenImgBatch',
            ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
            ocr__normal__pb2.OCRSerBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LocateTextAdvBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/LocateTextAdvBatch',
            ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
            ocr__normal__pb2.TextLocateBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SensitiveWords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/SensitiveWords',
            ocr__normal__pb2.OCRSerReq.SerializeToString,
            ocr__normal__pb2.SensitiveWordsRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SensitiveWordsBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/SensitiveWordsBatch',
            ocr__normal__pb2.OCRSerBatchReq.SerializeToString,
            ocr__normal__pb2.SensitiveWordsBatchRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/PredictVideo',
            ocr__normal__pb2.VideoPredictReq.SerializeToString,
            ocr__normal__pb2.TagPredictRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ocr.OCRService/PredictImages',
            ocr__normal__pb2.ImagesPredictReq.SerializeToString,
            ocr__normal__pb2.MTagPredictRsp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
