# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ocr_ehd_warp.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ocr_ehd_warp.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12ocr_ehd_warp.proto\x12\x0cocr_ehd_warp\x1a\nbase.proto\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"w\n\x04Poly\x12#\n\x06\x62ounds\x18\x01 \x03(\x0b\x32\x13.ocr_ehd_warp.Point\x12#\n\x06points\x18\x02 \x03(\x0b\x32\x13.ocr_ehd_warp.Point\x12\x11\n\tpoly_prob\x18\x03 \x01(\x01\x12\x12\n\nimage_page\x18\x04 \x01(\x0c\"\xdd\x01\n\nOcrRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x11\n\timage_url\x18\x02 \x01(\t\x12\x12\n\nimage_name\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\x12:\n\tparameter\x18\x05 \x03(\x0b\x32\'.ocr_ehd_warp.OcrRequest.ParameterEntry\x12\x18\n\x04\x62\x61se\x18\x06 \x01(\x0b\x32\n.base.Base\x1a\x30\n\x0eParameterEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"e\n\x0bOcrResponse\x12\x10\n\x08num_poly\x18\x01 \x01(\x05\x12!\n\x05pages\x18\x02 \x03(\x0b\x32\x12.ocr_ehd_warp.Poly\x12!\n\tbase_resp\x18\x03 \x01(\x0b\x32\x0e.base.BaseResp2S\n\x11OcrEHDWarpService\x12>\n\x07OcrWarp\x12\x18.ocr_ehd_warp.OcrRequest\x1a\x19.ocr_ehd_warp.OcrResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ocr_ehd_warp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OCRREQUEST_PARAMETERENTRY']._loaded_options = None
  _globals['_OCRREQUEST_PARAMETERENTRY']._serialized_options = b'8\001'
  _globals['_POINT']._serialized_start=48
  _globals['_POINT']._serialized_end=77
  _globals['_POLY']._serialized_start=79
  _globals['_POLY']._serialized_end=198
  _globals['_OCRREQUEST']._serialized_start=201
  _globals['_OCRREQUEST']._serialized_end=422
  _globals['_OCRREQUEST_PARAMETERENTRY']._serialized_start=374
  _globals['_OCRREQUEST_PARAMETERENTRY']._serialized_end=422
  _globals['_OCRRESPONSE']._serialized_start=424
  _globals['_OCRRESPONSE']._serialized_end=525
  _globals['_OCREHDWARPSERVICE']._serialized_start=527
  _globals['_OCREHDWARPSERVICE']._serialized_end=610
# @@protoc_insertion_point(module_scope)
