# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import workflow_worker.interfaces.api.workflow_manager_pb2 as workflow__manager__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobManagerServiceStub(object):
    """JobManagerService exposes interfaces for fetching jobs and submitting results.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetJob = channel.unary_unary(
                '/workflow.manager.JobManagerService/GetJob',
                request_serializer=workflow__manager__pb2.GetJobRequest.SerializeToString,
                response_deserializer=workflow__manager__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.CreateReport = channel.unary_unary(
                '/workflow.manager.JobManagerService/CreateReport',
                request_serializer=workflow__manager__pb2.CreateReportRequest.SerializeToString,
                response_deserializer=workflow__manager__pb2.CreateReportResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/workflow.manager.JobManagerService/Heartbeat',
                request_serializer=workflow__manager__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=workflow__manager__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class JobManagerServiceServicer(object):
    """JobManagerService exposes interfaces for fetching jobs and submitting results.
    """

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateReport(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobManagerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=workflow__manager__pb2.GetJobRequest.FromString,
                    response_serializer=workflow__manager__pb2.GetJobResponse.SerializeToString,
            ),
            'CreateReport': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateReport,
                    request_deserializer=workflow__manager__pb2.CreateReportRequest.FromString,
                    response_serializer=workflow__manager__pb2.CreateReportResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=workflow__manager__pb2.HeartbeatRequest.FromString,
                    response_serializer=workflow__manager__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow.manager.JobManagerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow.manager.JobManagerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobManagerService(object):
    """JobManagerService exposes interfaces for fetching jobs and submitting results.
    """

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.manager.JobManagerService/GetJob',
            workflow__manager__pb2.GetJobRequest.SerializeToString,
            workflow__manager__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateReport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.manager.JobManagerService/CreateReport',
            workflow__manager__pb2.CreateReportRequest.SerializeToString,
            workflow__manager__pb2.CreateReportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.manager.JobManagerService/Heartbeat',
            workflow__manager__pb2.HeartbeatRequest.SerializeToString,
            workflow__manager__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
