# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: workflow_manager.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'workflow_manager.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import workflow_common_pb2 as workflow__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16workflow_manager.proto\x12\x10workflow.manager\x1a\x15workflow_common.proto\"\"\n\rGetJobRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\"<\n\x0eGetJobResponse\x12*\n\x08job_info\x18\x01 \x01(\x0b\x32\x18.workflow.common.JobInfo\"f\n\x13\x43reateReportRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x0f\n\x07task_id\x18\x02 \x01(\x04\x12.\n\njob_report\x18\x03 \x01(\x0b\x32\x1a.workflow.common.JobReport\"g\n\x14\x43reateReportResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x0f\n\x07task_id\x18\x02 \x01(\x04\x12.\n\njob_report\x18\x03 \x01(\x0b\x32\x1a.workflow.common.JobReport\">\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x17\n\x0frunning_job_ids\x18\x02 \x03(\x04\"&\n\x11HeartbeatResponse\x12\x11\n\tworker_id\x18\x01 \x01(\t2\x9b\x02\n\x11JobManagerService\x12M\n\x06GetJob\x12\x1f.workflow.manager.GetJobRequest\x1a .workflow.manager.GetJobResponse\"\x00\x12_\n\x0c\x43reateReport\x12%.workflow.manager.CreateReportRequest\x1a&.workflow.manager.CreateReportResponse\"\x00\x12V\n\tHeartbeat\x12\".workflow.manager.HeartbeatRequest\x1a#.workflow.manager.HeartbeatResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'workflow_manager_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETJOBREQUEST']._serialized_start=67
  _globals['_GETJOBREQUEST']._serialized_end=101
  _globals['_GETJOBRESPONSE']._serialized_start=103
  _globals['_GETJOBRESPONSE']._serialized_end=163
  _globals['_CREATEREPORTREQUEST']._serialized_start=165
  _globals['_CREATEREPORTREQUEST']._serialized_end=267
  _globals['_CREATEREPORTRESPONSE']._serialized_start=269
  _globals['_CREATEREPORTRESPONSE']._serialized_end=372
  _globals['_HEARTBEATREQUEST']._serialized_start=374
  _globals['_HEARTBEATREQUEST']._serialized_end=436
  _globals['_HEARTBEATRESPONSE']._serialized_start=438
  _globals['_HEARTBEATRESPONSE']._serialized_end=476
  _globals['_JOBMANAGERSERVICE']._serialized_start=479
  _globals['_JOBMANAGERSERVICE']._serialized_end=762
# @@protoc_insertion_point(module_scope)
