
from typing import Any

from workflow_worker.domain.entities.tasks.common.ocr.result import OCRTrackingResult
from workflow_worker.domain.entities.tasks.document_recognition.config import (
    DocumentRecognitionJobCfg,
    SingleDocumentRecognitionJobCfg,
)
from workflow_worker.domain.entities.tasks.document_recognition.result import (
    DocOCRRecogResult,
    DocumentRecognitionJobResult,
)
from workflow_worker.domain.entities.rule import RulePoint
from workflow_worker.domain.entities.service.ocr import OCRInfoType
from workflow_worker.domain.entities.task import Task
from workflow_worker.applications.jobs.common.ocr.ocr_id_generator import OCRIDGenerator
from workflow_worker.applications.jobs.common.ocr.ocr_info_manager import DocOCRInfoManager
from workflow_worker.shared.logging._logging import get_logger
from workflow_worker.services.ai.ocr import DocumentOCRService
from workflow_worker.shared.utils.frame import (
    decode_image,
    encode_image,
    get_image_bytes,
    get_storage_url,
)
from workflow_worker.shared.utils.media import gather_batch_frames
from workflow_worker.shared.utils.visualization import draw_box, draw_polygon
from workflow_worker.applications.workflows.task_context import TaskContext

logger = get_logger(__name__)


class DocumentRecognitionJob:
    """Document quality inspection task"""

    def __init__(self) -> None:
        self.required_jobs: list[Any] = []
        self.id_generator = OCRIDGenerator()
        self.doc_tracker: DocOCRInfoManager | None = None
        self.id_mapper: dict[str, Any] = {}
        self.task_uuid: str = ""

    def parse_task(self, task: Task) -> DocumentRecognitionJobCfg:
        self.task_uuid = str(task.id)
        fps = task.rule.fps if task.rule else 2.0
        self.doc_tracker = DocOCRInfoManager(ocr_type=OCRInfoType.DOC_OCR_TYPE, fps=fps)
        configs = []
        if task.rule:
            for rule_section in task.rule.rule_sections:
                for rule_point in rule_section.rule_points:
                    if rule_point:
                        configs.extend(self._get_doc_recog_cfg(rule_point))
        return DocumentRecognitionJobCfg(fps=fps, batch_size=10, media=task.media, configs=configs)

    def _get_doc_recog_cfg(self, rule_point: RulePoint) -> list[SingleDocumentRecognitionJobCfg]:
        """Parse doc recog config from rule_point.

        Args:
            rule_point (RulePoint): The rule point needs to check.
        """
        doc_cfgs: list[Any] = []
        if not rule_point.document_cfgs:
            return doc_cfgs
        # Parse doc cfgs from document_cfgs
        for cfg in rule_point.document_cfgs:
            if not cfg:
                continue
            title = cfg.document_title
            detect_threshold = cfg.document_detection_threshold
            detect_threshold = 0.7 if detect_threshold < 0 else detect_threshold
            need_recog = False
            if title:
                doc_id, flag = self.id_generator.get_ocr_id(
                    "documents", {"title": {"text": title}}
                )
                # Skip if the content has been registed
                if flag:
                    continue
                # Build the matching relation between rule_point uuid & doc_id
                self.id_mapper[doc_id] = rule_point.id
                need_recog = True
            else:
                doc_id = self.id_generator.get_detection_ocr_id(
                    OCRInfoType.DOC_OCR_TYPE
                )
            single_cfg = SingleDocumentRecognitionJobCfg(
                id=rule_point.id,
                frame_infos={},
                title=title,
                doc_id=doc_id,
                detection_threshold=detect_threshold,
                recog_threshold=cfg.document_title_threshold,
                need_recog=need_recog,
            )
            doc_cfgs.append(single_cfg)
        return doc_cfgs

    def run(self, job_cfg: DocumentRecognitionJobCfg, task_context: TaskContext) -> DocumentRecognitionJobResult:
        """Run the document recognition job. Parse & register document info from job_cfg
        & foreach frames in fps to extract document & title, then push it into tracker
        to generate job_results.

        Args:
            job_cfg (DocumentRecognitionJobCfg): The job configs.
            task_context (TaskContext): The global task context.

        Returns:
            DocumentRecognitionJobResult: The job result generated by tracker.
        """

        ai_result: list[Any] = []
        job_results: list[Any] = []

        # Register doc contents into doc_tracker
        assert self.doc_tracker is not None
        self._register(job_cfg)

        # Grab video & frame infos from job_cfg
        fps = job_cfg.fps
        batch_size = job_cfg.batch_size
        video_path = job_cfg.media.path
        media_meta = job_cfg.media.meta
        height = media_meta.height if media_meta else 0
        width = media_meta.width if media_meta else 0

        # Abort when job_cfg is empty
        if len(job_cfg.configs) <= 0:
            return DocumentRecognitionJobResult(ai_result=ai_result, results=job_results)

        # Init doc service
        doc_service = DocumentOCRService(job_cfg.configs[0].detection_threshold or 0.75)

        tracking_results = []
        # Gathre frames in batch_size count.
        for frames in gather_batch_frames(video_path, width, height, int(fps), batch_size):
            doc_ocr_results = doc_service.run(frames)
            for ocr_result, frame in zip(doc_ocr_results, frames.frames):
                tracking_result = self.doc_tracker.process(ocr_result, frame)
                if tracking_result:
                    tracking_results.append(tracking_result)

        # Make sure all doc tracking result published.
        tracking_result = self.doc_tracker.over()
        if tracking_result:
            tracking_results.append(tracking_result)

        # Parse job_results & ai_result
        for tracking_result in tracking_results:
            id, job_result = self._parse(tracking_result)
            img_bytes = get_image_bytes(job_result.frame)
            if img_bytes is not None:
                cv_img = decode_image(img_bytes)  # pyright: ignore[reportArgumentType]
                bbox = job_result.bbox
                if bbox and len(bbox) == 4:
                    draw_box(cv_img, bbox, (0, 255, 0))
                elif bbox and len(bbox) == 8:
                    draw_polygon(cv_img, bbox, (0, 255, 0))
                drawed_img_bytes = encode_image(cv_img)
                url = get_storage_url(self.task_uuid, drawed_img_bytes)
                job_result.url = url
                job_result.frame.url = url
                job_result.frame.data = None
            ai_result.append(job_result)
            job_results.append((id, job_result))
        return DocumentRecognitionJobResult(ai_result=ai_result, results=job_results)

    def _register(self, job_cfg: DocumentRecognitionJobCfg):
        """Register doc contents into job_tracker.

        Args:
            job_cfg (DocumentRecognitionJobCfg): The job configs parse from task.
        """
        assert self.doc_tracker is not None
        for cfg in job_cfg.configs:
            doc_contents = {}
            # Fill recognition content when recognition is needed
            if cfg.need_recog:
                doc_contents["title"] = {
                    "text": cfg.title,
                    "similarity_threshold": cfg.recog_threshold,
                }
                self.doc_tracker.need_recognition = True

            self.doc_tracker.append_contents(
                cfg.doc_id, doc_contents, key_fields=["title"]
            )

    def _parse(
        self, tracking_result: OCRTrackingResult
    ) -> tuple[str, DocOCRRecogResult]:
        """Parse DocOCRRecogResult from OCRTrackingResult.

        Args:
            tracking_result (OCRTrackingResult): The ocr tracking result from
                ocr manager.

        Returns:
            tuple[str, DocOCRRecogResult]: The rule_point uuid & doc recog result.
                Set rule_point uuid as doc ocr detection_id when the OCRTrackingResult
                is detection result.
        """
        doc_id = tracking_result.tracking_id
        # Set rule_point_id as doc_id if doc_id has not registed(detection_ocr_id).
        rule_point_id = self.id_mapper.get(doc_id, doc_id)
        # Parse origin text from expected_contents
        origin_texts = []
        for content in tracking_result.expected_contents.values():
            origin_texts.append(content["text"])
        # Parse recog text & confidence from recoginized_contents
        recog_texts = []
        recog_confidences = []
        for content in tracking_result.recoginized_contents.values():
            recog_texts.append(content["text"])
            recog_confidences.append(content["similarity"])
        doc_ocr_recog_result = DocOCRRecogResult(
            frame=tracking_result.frame,
            time=tracking_result.time_patch,
            bbox=list(filter(None, tracking_result.bbox)) if tracking_result.bbox else [],  # pyright: ignore[reportArgumentType]
            detect_confidence=tracking_result.confidence or 0.0,
            origin_keys=tracking_result.keys,
            origin_texts=origin_texts,
            recog_texts=recog_texts,
            recog_confidence=recog_confidences,
        )
        return (rule_point_id, doc_ocr_recog_result)
