# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: face_body_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'face_body_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x66\x61\x63\x65_body_detection.proto\x12\tdetection\x1a\nbase.proto\"F\n\x08RespBase\x12\x14\n\x0ctime_elapsed\x18\x01 \x01(\x05\x12\x13\n\x0breceived_at\x18\x02 \x01(\x05\x12\x0f\n\x07sent_at\x18\x03 \x01(\x05\"5\n\x03\x42ox\x12\n\n\x02x1\x18\x01 \x01(\x05\x12\n\n\x02y1\x18\x02 \x01(\x05\x12\n\n\x02x2\x18\x03 \x01(\x05\x12\n\n\x02y2\x18\x04 \x01(\x05\"X\n\x06Object\x12\x10\n\x08\x63hn_name\x18\x01 \x01(\t\x12\x10\n\x08\x65ng_name\x18\x02 \x01(\t\x12\x1b\n\x03\x62ox\x18\x03 \x01(\x0b\x32\x0e.detection.Box\x12\r\n\x05score\x18\x04 \x01(\x01\"1\n\x07Request\x12\x0c\n\x04imgs\x18\x01 \x03(\x0c\x12\x18\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\n.base.Base\"s\n\x08Response\x12!\n\x06result\x18\x01 \x03(\x0b\x32\x11.detection.Object\x12!\n\x04\x62\x61se\x18\x02 \x01(\x0b\x32\x13.detection.RespBase\x12!\n\tbase_resp\x18\x03 \x01(\x0b\x32\x0e.base.BaseResp2F\n\x10\x44\x65tectionService\x12\x32\n\x07Predict\x12\x12.detection.Request\x1a\x13.detection.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'face_body_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPBASE']._serialized_start=52
  _globals['_RESPBASE']._serialized_end=122
  _globals['_BOX']._serialized_start=124
  _globals['_BOX']._serialized_end=177
  _globals['_OBJECT']._serialized_start=179
  _globals['_OBJECT']._serialized_end=267
  _globals['_REQUEST']._serialized_start=269
  _globals['_REQUEST']._serialized_end=318
  _globals['_RESPONSE']._serialized_start=320
  _globals['_RESPONSE']._serialized_end=435
  _globals['_DETECTIONSERVICE']._serialized_start=437
  _globals['_DETECTIONSERVICE']._serialized_end=507
# @@protoc_insertion_point(module_scope)
