# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: id_card_ocr.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'id_card_ocr.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import base_pb2 as base__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11id_card_ocr.proto\x12\x0bid_card_ocr\x1a\nbase.proto\"t\n\nCardOCRReq\x12\x10\n\x08req_name\x18\x01 \x01(\t\x12\x10\n\x08img_data\x18\x02 \x01(\x0c\x12(\n\tcard_type\x18\x03 \x01(\x0e\x32\x15.id_card_ocr.CardType\x12\x18\n\x04\x62\x61se\x18\x04 \x01(\x0b\x32\n.base.Base\"X\n\x0b\x45xtractInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x01\x12\x14\n\x0cinfo_corners\x18\x03 \x03(\x05\x12\x11\n\trecog_str\x18\x04 \x01(\t\"\xdb\x01\n\nCardOCRRsp\x12\x13\n\x0bis_detected\x18\x01 \x01(\x08\x12\x1f\n\x04side\x18\x02 \x01(\x0e\x32\x11.id_card_ocr.Side\x12\x14\n\x0c\x63\x61rd_corners\x18\x03 \x03(\x05\x12\x33\n\x11\x65xtract_info_list\x18\x04 \x03(\x0b\x32\x18.id_card_ocr.ExtractInfo\x12\x13\n\x0b\x63ropped_img\x18\x05 \x01(\x0c\x12\x14\n\x0c\x66\x61\x63\x65_corners\x18\x06 \x03(\x05\x12!\n\tbase_resp\x18\x07 \x01(\x0b\x32\x0e.base.BaseResp*=\n\x08\x43\x61rdType\x12\x15\n\x11\x43\x41RD_TYPE_UNKNOWN\x10\x00\x12\x0b\n\x07ID_CARD\x10\x01\x12\r\n\tBANK_CARD\x10\x02*-\n\x04Side\x12\x10\n\x0cSIDE_UNKNOWN\x10\x00\x12\t\n\x05\x46ront\x10\x01\x12\x08\n\x04\x42\x61\x63k\x10\x02\x32\x46\n\x07\x43\x61rdOCR\x12;\n\x07Predict\x12\x17.id_card_ocr.CardOCRReq\x1a\x17.id_card_ocr.CardOCRRspb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'id_card_ocr_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CARDTYPE']._serialized_start=476
  _globals['_CARDTYPE']._serialized_end=537
  _globals['_SIDE']._serialized_start=539
  _globals['_SIDE']._serialized_end=584
  _globals['_CARDOCRREQ']._serialized_start=46
  _globals['_CARDOCRREQ']._serialized_end=162
  _globals['_EXTRACTINFO']._serialized_start=164
  _globals['_EXTRACTINFO']._serialized_end=252
  _globals['_CARDOCRRSP']._serialized_start=255
  _globals['_CARDOCRRSP']._serialized_end=474
  _globals['_CARDOCR']._serialized_start=586
  _globals['_CARDOCR']._serialized_end=656
# @@protoc_insertion_point(module_scope)
