# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: media_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'media_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13media_service.proto\x12\x0eworkflow.media\"6\n\x04Word\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08start_ts\x18\x02 \x01(\x03\x12\x0e\n\x06\x65nd_ts\x18\x03 \x01(\x03\"`\n\tUtterance\x12\x0c\n\x04text\x18\x01 \x01(\t\x12#\n\x05words\x18\x02 \x03(\x0b\x32\x14.workflow.media.Word\x12\x10\n\x08start_ts\x18\x03 \x01(\x03\x12\x0e\n\x06\x65nd_ts\x18\x04 \x01(\x03\"s\n\x05\x41udio\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12-\n\nutterances\x18\x03 \x03(\x0b\x32\x19.workflow.media.Utterance\x12\x10\n\x08start_ts\x18\x04 \x01(\x03\x12\x0e\n\x06\x65nd_ts\x18\x05 \x01(\x03\"D\n\x05Image\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0b\n\x03url\x18\x02 \x01(\t\x12\n\n\x02ts\x18\x03 \x01(\x03\x12\x14\n\x0c\x66rame_number\x18\x04 \x01(\x04\":\n\x15\x46\x65tchMediaDataRequest\x12\x10\n\x08media_id\x18\x01 \x01(\x04\x12\x0f\n\x07timeout\x18\x02 \x01(\r\"\xe4\x01\n\x16\x46\x65tchMediaDataResponse\x12\"\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x14.workflow.media.Code\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0f\n\x07task_id\x18\x03 \x01(\x04\x12,\n\x06status\x18\x04 \x01(\x0e\x32\x1c.workflow.media.NotifyStatus\x12&\n\x05\x61udio\x18\x05 \x01(\x0b\x32\x15.workflow.media.AudioH\x00\x12&\n\x05image\x18\x06 \x01(\x0b\x32\x15.workflow.media.ImageH\x00\x42\x06\n\x04\x64\x61ta*=\n\x0cNotifyStatus\x12\n\n\x06normal\x10\x00\x12\n\n\x06\x66\x61iled\x10\x01\x12\n\n\x06\x66inish\x10\x02\x12\t\n\x05start\x10\x03*+\n\x04\x43ode\x12\x0b\n\x07unknown\x10\x00\x12\x0b\n\x07success\x10\x01\x12\t\n\x05\x65rror\x10\x02\x32q\n\x0cMediaService\x12\x61\n\x0e\x46\x65tchMediaData\x12%.workflow.media.FetchMediaDataRequest\x1a&.workflow.media.FetchMediaDataResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'media_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFYSTATUS']._serialized_start=671
  _globals['_NOTIFYSTATUS']._serialized_end=732
  _globals['_CODE']._serialized_start=734
  _globals['_CODE']._serialized_end=777
  _globals['_WORD']._serialized_start=39
  _globals['_WORD']._serialized_end=93
  _globals['_UTTERANCE']._serialized_start=95
  _globals['_UTTERANCE']._serialized_end=191
  _globals['_AUDIO']._serialized_start=193
  _globals['_AUDIO']._serialized_end=308
  _globals['_IMAGE']._serialized_start=310
  _globals['_IMAGE']._serialized_end=378
  _globals['_FETCHMEDIADATAREQUEST']._serialized_start=380
  _globals['_FETCHMEDIADATAREQUEST']._serialized_end=438
  _globals['_FETCHMEDIADATARESPONSE']._serialized_start=441
  _globals['_FETCHMEDIADATARESPONSE']._serialized_end=669
  _globals['_MEDIASERVICE']._serialized_start=779
  _globals['_MEDIASERVICE']._serialized_end=892
# @@protoc_insertion_point(module_scope)
