# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import workflow_proto.workflow_common_pb2 as workflow__common__pb2
import workflow_proto.workflow_worker_pb2 as workflow__worker__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobWorkerServiceStub(object):
    """JobWorkerService only exposes a stop interface, not a start interface.
    Workers proactively pull tasks from the manager.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StopRunningJob = channel.unary_unary(
                '/workflow.worker.JobWorkerService/StopRunningJob',
                request_serializer=workflow__common__pb2.JobInfo.SerializeToString,
                response_deserializer=workflow__worker__pb2.StopRunningJobResponse.FromString,
                _registered_method=True)
        self.PollEvents = channel.unary_unary(
                '/workflow.worker.JobWorkerService/PollEvents',
                request_serializer=workflow__worker__pb2.PollEventsRequest.SerializeToString,
                response_deserializer=workflow__worker__pb2.PollEventsResponse.FromString,
                _registered_method=True)


class JobWorkerServiceServicer(object):
    """JobWorkerService only exposes a stop interface, not a start interface.
    Workers proactively pull tasks from the manager.
    """

    def StopRunningJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StopRunningJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRunningJob,
                    request_deserializer=workflow__common__pb2.JobInfo.FromString,
                    response_serializer=workflow__worker__pb2.StopRunningJobResponse.SerializeToString,
            ),
            'PollEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.PollEvents,
                    request_deserializer=workflow__worker__pb2.PollEventsRequest.FromString,
                    response_serializer=workflow__worker__pb2.PollEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'workflow.worker.JobWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('workflow.worker.JobWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobWorkerService(object):
    """JobWorkerService only exposes a stop interface, not a start interface.
    Workers proactively pull tasks from the manager.
    """

    @staticmethod
    def StopRunningJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.worker.JobWorkerService/StopRunningJob',
            workflow__common__pb2.JobInfo.SerializeToString,
            workflow__worker__pb2.StopRunningJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/workflow.worker.JobWorkerService/PollEvents',
            workflow__worker__pb2.PollEventsRequest.SerializeToString,
            workflow__worker__pb2.PollEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
